export const IMAGE_DEFAULTS = {
  SITEKEY: '0x4AAAAAABpqJe8FO0N84q0F',
  COOLDOWN_DEFAULT: 31000,
  TRANSPARENCY_THRESHOLD: 100,
  WHITE_THRESHOLD: 250,
  LOG_INTERVAL: 10,
  TILE_SIZE: 3000,
  PIXELS_PER_BATCH: 20,
  CHARGE_REGEN_MS: 30000,
  THEME: {
    primary: '#000000',
    secondary: '#111111',
    accent: '#222222',
    text: '#ffffff',
    highlight: '#775ce3',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffaa00'
  }
};

export const TEXTS = {
  es: {
    title: "WPlace Auto-Image",
    initBot: "Iniciar Auto-BOT",
    uploadImage: "Subir Imagen",
    resizeImage: "Redimensionar Imagen",
    selectPosition: "Seleccionar Posición",
    startPainting: "Iniciar Pintura",
    stopPainting: "Detener Pintura",
    saveProgress: "Guardar Progreso",
    loadProgress: "Cargar Progreso",
    checkingColors: "🔍 Verificando colores disponibles...",
    noColorsFound: "❌ ¡Abre la paleta de colores en el sitio e inténtalo de nuevo!",
    colorsFound: "✅ {count} colores disponibles encontrados",
    loadingImage: "🖼️ Cargando imagen...",
    imageLoaded: "✅ Imagen cargada con {count} píxeles válidos",
    imageError: "❌ Error al cargar la imagen",
    selectPositionAlert: "¡Pinta el primer píxel en la ubicación donde quieres que comience el arte!",
    waitingPosition: "👆 Esperando que pintes el píxel de referencia...",
    positionSet: "✅ ¡Posición establecida con éxito!",
    positionTimeout: "❌ Tiempo agotado para seleccionar posición",
    startPaintingMsg: "🎨 Iniciando pintura...",
    paintingProgress: "🧱 Progreso: {painted}/{total} píxeles...",
    noCharges: "⌛ Sin cargas. Esperando {time}...",
    paintingStopped: "⏹️ Pintura detenida por el usuario",
    paintingComplete: "✅ ¡Pintura completada! {count} píxeles pintados.",
    paintingError: "❌ Error durante la pintura",
    missingRequirements: "❌ Carga una imagen y selecciona una posición primero",
    progress: "Progreso",
    pixels: "Píxeles",
    charges: "Cargas",
    estimatedTime: "Tiempo estimado",
    initMessage: "Haz clic en 'Iniciar Auto-BOT' para comenzar",
    waitingInit: "Esperando inicialización...",
    resizeSuccess: "✅ Imagen redimensionada a {width}x{height}",
    paintingPaused: "⏸️ Pintura pausada en la posición X: {x}, Y: {y}",
    pixelsPerBatch: "Píxeles por lote",
    cooldownWaiting: "⏳ Esperando {time} para continuar...",
    progressSaved: "✅ Progreso guardado como {filename}",
    progressLoaded: "✅ Progreso cargado: {painted}/{total} píxeles pintados",
    progressLoadError: "❌ Error al cargar progreso: {error}",
    progressSaveError: "❌ Error al guardar progreso: {error}",
    confirmSaveProgress: "¿Deseas guardar el progreso actual antes de detener?",
    saveProgressTitle: "Guardar Progreso",
    discardProgress: "Descartar",
    cancel: "Cancelar",
    minimize: "Minimizar",
    width: "Ancho",
    height: "Alto", 
    keepAspect: "Mantener proporción",
    apply: "Aplicar"
  }
};

export const imageState = {
  running: false,
  imageLoaded: false,
  processing: false,
  totalPixels: 0,
  paintedPixels: 0,
  availableColors: [],
  currentCharges: 0,
  cooldown: IMAGE_DEFAULTS.COOLDOWN_DEFAULT,
  imageData: null,
  stopFlag: false,
  colorsChecked: false,
  startPosition: null,
  selectingPosition: false,
  region: null,
  minimized: false,
  lastPosition: { x: 0, y: 0 },
  estimatedTime: 0,
  language: 'es',
  tileX: null,
  tileY: null,
  pixelsPerBatch: IMAGE_DEFAULTS.PIXELS_PER_BATCH,
  inCooldown: false,
  cooldownEndTime: 0,
  remainingPixels: [],
  lastChargeUpdate: 0,
  chargeDecimalPart: 0,
  originalImageName: null
};
